Improve scripts

diff --git a/auto_mate b/auto_mate
--- a/auto_mate
+++ b/auto_mate
@@ -7,30 +7,33 @@
 #
 # this will create a pow file, a apache virtual host file, restart apache, restart pow.
 
-if [ -z $1 ]; then
-    echo "...Directory name is required"
-    exit
-else
-    echo "...Creating virtual-host for ${1}"
+# User must specify a directory
+read -p "Project name: " project
+
+if [ ! ${project} ]; then
+    echo "Project name is required"
+    exit 1
 fi
+
+# User must specify an optional subfolder
+read -p "Subfolder (or press enter to leave blank): " sub_directory
 
 sub=""
 
-if ! [[ -z $2 ]]; then
-  echo "...Subfolder '${2}' was provided"
-  sub="/$2"
+if [[ ${sub_directory} ]]; then
+  sub="/${sub_directory}"
 fi
 
 sudo echo "<VirtualHost *:80>
-    DocumentRoot '/Users/mike/code/${1}${sub}'
-    ServerName ${1}.dev
-</VirtualHost>" > /etc/apache2/sites-available/"${1}".conf
+    DocumentRoot '${HOME}/code/${project}${sub}'
+    ServerName ${project}.dev
+</VirtualHost>" > /etc/apache2/sites-available/"${project}".conf
 
-sudo ln -s /etc/apache2/sites-available/"${1}".conf /etc/apache2/sites-enabled/"${1}".conf
-sudo echo '127.0.0.1:80' > ~/.pow/"${1}"
+sudo ln -s /etc/apache2/sites-available/${project}.conf /etc/apache2/sites-enabled/${project}.conf
+sudo echo '127.0.0.1:80' > ~/.pow/${project}
 sudo apachectl restart
 powder up
 
-echo "...Environment ready. Go to: ${1}.dev"
+echo "Environment ready. Go to: ${project}.dev"
 
-exit
+exit 0
diff --git a/clean_downloads b/clean_downloads
--- a/clean_downloads
+++ b/clean_downloads
@@ -6,46 +6,63 @@
 #
 # This will clean your downloads for you.
 
-downloads=(/Users/mike/Downloads/*)
+in_array() {
+
+    # echo ${1}[@]
+    # exit
+
+    local haystack=${1}[@]
+    local needle=${2}
+
+    echo ${!haystack}
+    exit
+
+    for i in ${!haystack}; do
+        if [[ ${i} == ${needle} ]]; then
+            return 0
+        fi
+    done
+
+    return 1
+}
+
+downloads=(${HOME}/Downloads/*)
 
 IFS=$'\n' read -d '' -r -a items < $1
 
-# for each dir in Downloads
-for (( i = 0; i < ${#downloads[@]}; i++ )); do
+for (( j=0; j<${#downloads[@]}; j++ )); do
 
-    # get the dir name
-    dir="${downloads[$i]##*/}"
-    # replace dir name with periods
-    dir_name=${dir// /.}
+    dir_original_name="${downloads[$j]##*/}"
+    downloads_directory_name=${downloads[$j]}
+    dir_name=${dir_original_name// /.}
 
-    # for each item in array
-    for (( j = 0; j < ${#items[@]}; j++ )); do
+    if in_array items ${dir_name}; then
 
-        # check if part of the name of the dir matches any in the array
-        # @todo - make case insensitive
-        if [[ "${dir_name}" == *"${items[$j]}"* ]]; then
+        media_dir_location="${HOME}/media/${dir_name}"
 
-            # @todo - allow for spaces
-
-            # if it does, then go in to the dir
-            for file in "${downloads[$i]}"/*; do
-                if [[
-                    "${file}" == *".mkv"* ||
-                    "${file}" == *".mp4"* ||
-                    "${file}" == *".avi"*
-                ]]; then
-                    # @todo - check file does not already exist
-                    # @todo - check folder already exists. create it if it doesn't
-                    echo "moving $file to /Users/mike/media/${items[$j]}/"
-                    # and move them in to a dir with the same name from the array element that was matched
-                    mv $file "/Users/mike/media/${items[$j]}/"
+        for file in "${downloads_directory_name}"/*; do
+            if [[
+                "${file}" == *".mkv"* ||
+                "${file}" == *".mp4"* ||
+                "${file}" == *".avi"*
+            ]]; then
+                if [[ ! -d ${media_dir_location} ]]; then
+                    if mkdir ${media_dir_location}; then
+                        echo "Created new directory in /media called: ${dir_name}."
+                    else
+                        echo "Error: Could not create ${dir_name} in /media."
+                        exit 1
+                    fi
                 fi
-            done
 
-            # then after you've taken everything, just delete that directory
-            rm -rf "${downloads[$i]}"
-        fi
-    done
+                echo "Moving the file ${file} to ${media_dir_location}."
+                mv ${file} ${media_dir_location}
+            fi
+        done
+
+        echo "Deleting the directory: ${downloads_directory_name}"
+        rm -rf ${downloads_directory_name}
+    fi
 done
 
-exit
+exit 0
